version: '3.1'
services:
  app:
    container_name: tenpo-app
    image: tenpo-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=tenpo
      - POSTGRES_DB=math_db